//////////////// id's dos canais do discord

module.exports = {
    TOKEN: 'TOKEN DO BOT',
    CLIENT_ID: 'ID DO CLIENTE HIHIHI',
    GUILD_ID: 'ID DO SERVIDOR',
    ADMIN_ROLE:'ID DA ROLE DE ADMIN',
    USER_ROLE: 'ID DA ROLE DE USUARIO',
    START_CHANNEL_ID: 'ID DO CANAL DE COMEÇO',
    CHANNEL_CAIXA: 'CAIXA DA EMPRESA',
    CHANNEL_SAIDAS: 'SAIDAS',
    FINALIZED_CHANNEL_ID: "CANAL DE FINALIZADOS",
    CHANNEL_CLIENTES: 'CANAL DE CLIENTES',
    CHANNEL_PRODUTOS: 'CANAL DE PRODUTOS',
    CHANNEL_ESTOQUE: 'CANAL DE ESTOQUE'
 };


